// Current Weather
export const GET_CURRENT_WEATHER_BY_ZIP = "GET_CURRENT_WEATHER_BY_ZIP";
export const GET_CURRENT_WEATHER_BY_CITY = "GET_CURRENT_WEATHER_BY_CITY";
export const CLEAR_CURRENT_WEATHER = "CLEAR_CURRENT_WEATHER";

// Forecast
export const GET_FORECAST_BY_ZIP = "GET_FORECAST_BY_ZIP";
export const GET_FORECAST_BY_CITY = "GET_FORECAST_BY_CITY";
export const CLEAR_FORECAST = "CLEAR_FORECAST";

// Error
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_ERROR = "SET_ERROR";