export const GET_CURRENT_WEATHER_BY_ZIP = "GET_CURRENT_WEATHER_BY_ZIP";
export const GET_CURRENT_WEATHER_BY_CITY = "GET_CURRENT_WEATHER_BY_CITY";
export const DELETE_CURRENT_WEATHER = "DELETE_CURRENT_WEATHER";